//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApplication.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECommerce : DbContext
    {
        public ECommerce()
            : base("name=ECommerce")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductInfo> ProductInfoes { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<CustomerLastLogin> CustomerLastLogins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    
        public virtual ObjectResult<getUserByDate_Result> getUserByDate(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserByDate_Result>("getUserByDate", customerIDParameter);
        }
    
        public virtual ObjectResult<usps_LastUserLogin_Result> usps_LastUserLogin(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_LastUserLogin_Result>("usps_LastUserLogin", customerIDParameter);
        }
    
        public virtual ObjectResult<usps_Role_Result> usps_Role()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_Role_Result>("usps_Role");
        }
    
        public virtual ObjectResult<usps_Customers_Result> usps_Customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_Customers_Result>("usps_Customers");
        }
    
        public virtual ObjectResult<usps_UserLogInDetails_Result> usps_UserLogInDetails(string customerList, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var customerListParameter = customerList != null ?
                new ObjectParameter("CustomerList", customerList) :
                new ObjectParameter("CustomerList", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_UserLogInDetails_Result>("usps_UserLogInDetails", customerListParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<usps_OrderDetails_Result> usps_OrderDetails(string customerList, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var customerListParameter = customerList != null ?
                new ObjectParameter("CustomerList", customerList) :
                new ObjectParameter("CustomerList", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_OrderDetails_Result>("usps_OrderDetails", customerListParameter, fromDateParameter, toDateParameter);
        }
    
        [DbFunction("ECommerce", "splitintotable")]
        public virtual IQueryable<splitintotable_Result> splitintotable(string arg, string delimiter)
        {
            var argParameter = arg != null ?
                new ObjectParameter("arg", arg) :
                new ObjectParameter("arg", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<splitintotable_Result>("[ECommerce].[splitintotable](@arg, @delimiter)", argParameter, delimiterParameter);
        }
    }
}
