//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApplication.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECommerce : DbContext
    {
        public ECommerce()
            : base("name=ECommerce")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductInfo> ProductInfoes { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<CustomerLastLogin> CustomerLastLogins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    
        public virtual ObjectResult<getUserByDate_Result> getUserByDate(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserByDate_Result>("getUserByDate", customerIDParameter);
        }
    
        public virtual ObjectResult<usps_LastUserLogin_Result> usps_LastUserLogin(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_LastUserLogin_Result>("usps_LastUserLogin", customerIDParameter);
        }
    
        public virtual ObjectResult<usps_Role_Result> usps_Role()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_Role_Result>("usps_Role");
        }
    
        public virtual ObjectResult<usps_Customers_Result> usps_Customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usps_Customers_Result>("usps_Customers");
        }
    }
}
